import { ResumeData, StyleSettings } from './types';

export const LAYOUT_OPTIONS = [
  { value: 'minimalist', label: 'Minimalista' },
  { value: 'executive', label: 'Ejecutivo' },
  { value: 'creative', label: 'Creativo' },
  { value: 'modern', label: 'Moderno' },
  { value: 'technical', label: 'Técnico' },
  { value: 'infographic', label: 'Infográfico' },
  { value: 'corporate', label: 'Corporativo' },
  { value: 'dual-column', label: 'Columna Dual' },
  { value: 'centered', label: 'Centrado' },
  { value: 'academic', label: 'Académico' },
  { value: 'banner', label: 'Con Banner' },
];

export const PREDEFINED_THEMES: { name: string; styles: Partial<StyleSettings> }[] = [
  {
    name: "Azul Océano",
    styles: {
      headerColor: "#0f172a",
      textColor: "#334155",
      borderColor: "#0ea5e9",
      fontFamily: "Inter",
      sectionTitleColor: "#0ea5e9",
      skillBackgroundColor: "#e0f2fe",
      skillTextColor: "#075985",
    },
  },
  {
    name: "Menta Ejecutivo",
    styles: {
      headerColor: "#047857",
      textColor: "#1f2937",
      borderColor: "#34d399",
      fontFamily: "Lora",
      sectionTitleColor: "#047857",
      skillBackgroundColor: "#d1fae5",
      skillTextColor: "#064e3b",
    },
  },
  {
    name: "Púrpura Tecnológico",
    styles: {
      sheetColor: "#1e1b4b",
      headerColor: "#5b21b6",
      textColor: "#e5e7eb",
      borderColor: "#a78bfa",
      fontFamily: "Source Code Pro",
      sectionTitleColor: "#a78bfa",
      skillBackgroundColor: "#3730a3",
      skillTextColor: "#e0e7ff",
    },
  },
  {
    name: "Gris Minimalista",
    styles: {
      headerColor: "#4b5563",
      textColor: "#111827",
      borderColor: "#d1d5db",
      fontFamily: "Inter",
      sectionTitleColor: "#4b5563",
      skillBackgroundColor: "#e5e7eb",
      skillTextColor: "#1f2937",
    },
  },
  {
    name: "Naranja Creativo",
    styles: {
      headerColor: "#f97316",
      textColor: "#44403c",
      borderColor: "#fb923c",
      fontFamily: "Roboto Slab",
      sectionTitleColor: "#f97316",
      skillBackgroundColor: "#ffedd5",
      skillTextColor: "#9a3412",
    },
  },
  {
    name: "Neón Noir",
    styles: {
      sheetColor: "#0a0a0a",
      headerColor: "#0a0a0a",
      textColor: "#e5e7eb",
      borderColor: "#33ffcc",
      fontFamily: "Source Code Pro",
      sectionTitleColor: "#33ffcc",
      skillBackgroundColor: "#1f2937",
      skillTextColor: "#33ffcc",
    },
  },
  {
    name: "Rojo Corporativo",
    styles: {
      headerColor: "#8b0000",
      textColor: "#1f2937",
      borderColor: "#dc2626",
      fontFamily: "Lora",
      sectionTitleColor: "#b91c1c",
      skillBackgroundColor: "#fee2e2",
      skillTextColor: "#991b1b",
    },
  },
  {
    name: "Tierra Orgánica",
    styles: {
      sheetColor: "#f0fdf4",
      headerColor: "#f0fdf4",
      textColor: "#3f6212",
      borderColor: "#84cc16",
      fontFamily: "Inter",
      sectionTitleColor: "#3f6212",
      skillBackgroundColor: "#d9f99d",
      skillTextColor: "#3f6212",
    },
  },
  {
    name: "Cielo Académico",
    styles: {
      sheetColor: "#e0f2fe",
      headerColor: "#e0f2fe",
      textColor: "#075985",
      borderColor: "#38bdf8",
      fontFamily: "Lora",
      sectionTitleColor: "#075985",
      skillBackgroundColor: "#bae6fd",
      skillTextColor: "#082f49",
    },
  },
  {
    name: "Verde Bosque",
    styles: {
      sheetColor: "#f0fdf4",
      headerColor: "#1A4314",
      textColor: "#14532d",
      borderColor: "#558B2F",
      fontFamily: "Lora",
      sectionTitleColor: "#558B2F",
      skillBackgroundColor: "#2E7D32",
      skillTextColor: "#E8F5E9",
    },
  },
  {
    name: "Dorado Lujo",
    styles: {
      sheetColor: "#fffaf0",
      headerColor: "#1c1c1c",
      textColor: "#333333",
      borderColor: "#D4AF37",
      fontFamily: "Lora",
      sectionTitleColor: "#B8860B",
      skillBackgroundColor: "#F5E6B8",
      skillTextColor: "#4B3B0A",
    },
  },
  {
    name: "Ciberpunk",
    styles: {
      sheetColor: "#1a1a1a",
      headerColor: "#0c0c0c",
      textColor: "#ecf0f1",
      borderColor: "#ff00ff",
      fontFamily: "Source Code Pro",
      sectionTitleColor: "#00ffff",
      skillBackgroundColor: "#ff00ff",
      skillTextColor: "#000000",
    },
  },
  {
    name: "Lavanda Suave",
    styles: {
      sheetColor: "#FFFFFF",
      headerColor: "#E6E6FA",
      textColor: "#483D8B",
      borderColor: "#9370DB",
      fontFamily: "Inter",
      sectionTitleColor: "#6A5ACD",
      skillBackgroundColor: "#E6E6FA",
      skillTextColor: "#483D8B",
    },
  },
  {
    name: "Coral Vivo",
    styles: {
      sheetColor: "#FFFFFF",
      headerColor: "#FF6F61",
      textColor: "#333333",
      borderColor: "#FFDAB9",
      fontFamily: "Roboto Slab",
      sectionTitleColor: "#FF4500",
      skillBackgroundColor: "#FFDAB9",
      skillTextColor: "#8B4513",
    },
  },
];


export const INITIAL_RESUME_DATA: ResumeData = {
  personal: {
    name: '',
    title: '',
    email: { value: '', link: '' },
    email2: { value: '', link: '' },
    phone: { value: '', link: '' },
    phone2: { value: '', link: '' },
    linkedin: { value: '', link: '' },
    definingPhrase: '',
  },
  summary: '',
  achievements: '',
  strengths: '',
  skills: '',
  experience: [{ id: crypto.randomUUID(), title: '', company: '', date: '', description: '' }],
  education: [{ id: crypto.randomUUID(), degree: '', school: '', date: '' }],
  style: {
    layout: 'modern',
    sheetColor: '#FFFFFF',
    textColor: '#334155',
    borderColor: '#0ea5e9',
    headerBackgroundType: 'color',
    headerColor: '#0f172a',
    headerImageUrl: '',
    profilePictureUrl: '',
    profilePictureShape: 'circle',
    profilePicturePosition: 'center',
    profilePictureSize: 128,
    fontFamily: 'Inter',
    sectionTitleColor: '#0ea5e9',
    skillBackgroundColor: '#e0f2fe',
    skillTextColor: '#075985',
  },
  jobDescription: '',
  jobDescriptionUrl: '',
  cvInput: '',
  cvInputUrl: '',
  aiAnalysis: null,
  coverLetter: '',
  coverLetterStyle: {
    fontFamily: 'Lora',
    fontSize: 12,
    textColor: '#334155',
  },
  cta: '',
};